name: flex_seed_scheme_example
description: Example that demonstrate how to use the FlexSeedScheme package.
version: 3.0.0
publish_to: 'none'
environment:
#  sdk: '>=3.0.0 <4.0.0'
#  flutter: '3.22.0'
  sdk: '>=2.19.6 <4.0.0'
  flutter: '>=3.7.12-ohos'

dependencies:
  # Add Cupertino Icons font to your application. Used by the
  # CupertinoIcons class for iOS style icons, by Google flutter.dev.
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.6

  # Color picker package, by Mike Rydstrom, rydmike.com (@rydmike).
  # Used for color selection in the Playground to make customized color schemes.
  # https://pub.dev/packages/flex_color_picker
#  flex_color_picker: ^3.5.0
  flex_color_picker: ^3.3.1

  # FlexSeedScheme package, by Mike Rydstrom, rydmike.com (@rydmike).
  # https://pub.dev/packages/flex_seed_scheme
  flex_seed_scheme:
    path: ../

  # The Flutter SDK, by Google flutter.dev.
  flutter:
    sdk: flutter

  # Used for launching a WEB URL, by Google flutter.dev.
  # https://pub.dev/packages/url_launcher
#  url_launcher: ^6.3.0
  url_launcher:
    git:
      url: https://gitee.com/openharmony-sig/flutter_packages.git
      path: packages/url_launcher/url_launcher

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  flex_seed_scheme:
    path: ../
